/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9rUEuKYi3zJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import Link from "next/link"
import Img from 'next/image';

export function Library() {
  return (
    <div className="w-full max-w-6xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <div >
        <div className="flex flex-col items-center mb-8">
          <h6 className="text-sm text-muted-foreground mb-2">Can&apos;t find what you&apos;re looking for?</h6>
          <Input
          type="search"
          placeholder="Search flashcard decks..."
          className="w-full rounded-lg bg-muted px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:ring-opacity-50"
        />
      </div>

      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <Link href="#" className="group" prefetch={false}>
          <div className="bg-muted rounded-lg overflow-hidden shadow-md transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg">
            <Img
              src="/Math.jpg"
              alt="Deck Cover"
              width="300"
              height="200"
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300">
                Math Fundamentals
              </h3>
              <p className="text-sm text-muted-foreground line-clamp-2">
                Explore the basic concepts of mathematics, from arithmetic to algebra.
              </p>
            </div>
          </div>
        </Link>
        <Link href="#" className="group" prefetch={false}>
          <div className="bg-muted rounded-lg overflow-hidden shadow-md transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg">
            <Img
              src="/History.jpg"
              alt="Deck Cover"
              width="300"
              height="200"
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300">
                History of Ancient Civilizations
              </h3>
              <p className="text-sm text-muted-foreground line-clamp-2">
                Journey through the rise and fall of the world&apos;s most influential ancient civilizations.
              </p>
            </div>
          </div>
        </Link>
        <Link href="#" className="group" prefetch={false}>
          <div className="bg-muted rounded-lg overflow-hidden shadow-md transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg">
            <Img
              src="/Coding.jpg"
              alt="Deck Cover"
              width="300"
              height="200"
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300">
                Introduction to Programming
              </h3>
              <p className="text-sm text-muted-foreground line-clamp-2">
                Learn the fundamentals of programming and coding with this comprehensive deck.
              </p>
            </div>
          </div>
        </Link>
        <Link href="#" className="group" prefetch={false}>
          <div className="bg-muted rounded-lg overflow-hidden shadow-md transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg">
            <Img
              src="/Health.jpg"
              alt="Deck Cover"
              width="300"
              height="200"
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300">
                Human Anatomy and Physiology
              </h3>
              <p className="text-sm text-muted-foreground line-clamp-2">
                Dive into the fascinating world of the human body and its inner workings.
              </p>
            </div>
          </div>
        </Link>
        <Link href="#" className="group" prefetch={false}>
          <div className="bg-muted rounded-lg overflow-hidden shadow-md transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg">
            <Img
              src="/Writing.jpg"
              alt="Deck Cover"
              width="300"
              height="200"
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300">
                Creative Writing Techniques
              </h3>
              <p className="text-sm text-muted-foreground line-clamp-2">
                Unlock your creative potential and master the art of storytelling.
              </p>
            </div>
          </div>
        </Link>
        <Link href="#" className="group" prefetch={false}>
          <div className="bg-muted rounded-lg overflow-hidden shadow-md transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg">
            <Img
              src="/GreenLife.jpg"
              alt="Deck Cover"
              width="300"
              height="200"
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300">
                Sustainable Living Practices
              </h3>
              <p className="text-sm text-muted-foreground line-clamp-2">
                Learn practical tips and strategies for living a more eco-friendly lifestyle.
              </p>
            </div>
          </div>
        </Link>
        <Link href="#" className="group" prefetch={false}>
          <div className="bg-muted rounded-lg overflow-hidden shadow-md transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg">
            <Img
              src="/Meditation.jpg"
              alt="Deck Cover"
              width="300"
              height="200"
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300">
                Mindfulness and Meditation
              </h3>
              <p className="text-sm text-muted-foreground line-clamp-2">
                Explore the benefits of mindfulness and learn effective meditation techniques.
              </p>
            </div>
          </div>
        </Link>
        <Link href="#" className="group" prefetch={false}>
          <div className="bg-muted rounded-lg overflow-hidden shadow-md transition-all duration-300 transform hover:-translate-y-1 hover:shadow-lg">
            <Img
              src="/Photography.jpg"
              alt="Deck Cover"
              width="300"
              height="200"
              className="w-full h-48 object-cover"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300">
                Photography Fundamentals
              </h3>
              <p className="text-sm text-muted-foreground line-clamp-2">
                Discover the art of photography and learn how to capture stunning images.
              </p>
            </div>
          </div>
        </Link>
      </div>
    </div>
  )
}
