/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/136B14ZGQPF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { SVGProps } from 'react';
import Img from 'next/image';

export function Price() {
return (
    <div className="flex flex-col min-h-[100dvh] justify-center items-center">
        <section className="w-full py-12 md:py-24 lg:py-32 container flex flex-col justify-center items-center h-screen text-center">
            <div className="container px-4 md:px-6">
                <div className="space-y-4 text-center">
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Pricing</h2>
                    <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                        Choose the plan that fits your needs and start learning with Flashcard AI today.
                    </p>
                </div>
                <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3 mt-12">
                    <Card className="space-y-4">
                        <CardHeader>
                            <CardTitle>Student - Free for first year</CardTitle>
                            <CardDescription>Perfect for individuals looking to boost their learning.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="flex items-baseline justify-center space-x-2">
                                <span className="text-4xl font-bold tracking-tight">$1.99</span>
                                <span className="text-muted-foreground">/ month</span>
                            </div>
                            <div className="mt-4 space-y-2">
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>500 flashcards per month</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Basic AI-powered learning</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Access to all question types</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Create or ask specific questions</span>
                                </div>
                            </div>
                        </CardContent>
                        <CardFooter>
                            <Button className="w-full">Get Started</Button>
                        </CardFooter>
                    </Card>
                    <Card className="space-y-4">
                        <CardHeader>
                            <CardTitle>Teacher</CardTitle>
                            <CardDescription>Ideal for professionals who need more advanced features.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="flex items-baseline justify-center space-x-2">
                                <span className="text-4xl font-bold tracking-tight">$5</span>
                                <span className="text-muted-foreground">/ month</span>
                            </div>
                            <div className="mt-4 space-y-2">
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Unlimited flashcards</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Advanced AI-powered learning</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Detailed performance analytics</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Priority support</span>
                                </div>
                            </div>
                        </CardContent>
                        <CardFooter>
                            <Button className="w-full">Get Started</Button>
                        </CardFooter>
                    </Card>
                    <Card className="space-y-4">
                        <CardHeader>
                            <CardTitle>Education Institution</CardTitle>
                            <CardDescription>Tailored for teams and organizations with advanced needs.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="flex items-baseline justify-center space-x-2">
                                <span className="text-4xl font-bold tracking-tight">$49</span>
                                <span className="text-muted-foreground">/ month</span>
                            </div>
                            <div className="mt-4 space-y-2">
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Unlimited flashcards and users</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Custom branding and integrations</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Dedicated account manager</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <CheckIcon className="h-4 w-4 text-primary" />
                                    <span>Advanced reporting and analytics</span>
                                </div>
                            </div>
                        </CardContent>
                        <CardFooter>
                            <Button className="w-full">Get Started</Button>
                        </CardFooter>
                    </Card>
                </div>
            </div>
        </section>
    </div>
)
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>): JSX.Element {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}
